#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN
//#define TAPPING_FORCE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#undef CONSOLE_ENABLE
#define FORCE_NKRO
#define COMBO_PERMISSIVE_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define MASTER_RIGHT
